import React from "react";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./lib/AntdRegistry";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ConfigProvider } from "antd";
import theme from "./theme/themeConfig";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ConfigProvider theme={theme}>
          <Header />
          {children}
          <Footer />
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
